tap "adoptopenjdk/openjdk"
tap "aws/tap"
tap "cloudflare/cloudflare"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "aws-iam-authenticator"
brew "awscli"
brew "bash-completion"
brew "bat"
brew "glib"
brew "python@3.9"
brew "unbound"
brew "gnutls"
brew "cask"
brew "cassandra", restart_service: true
brew "eksctl"
brew "ghostscript"
brew "gimme-aws-creds"
brew "git"
brew "go"
brew "groovy"
brew "shared-mime-info"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "libyaml"
brew "mas"
brew "minikube"
brew "mongosh"
brew "nvm"
brew "protobuf"
brew "mysql", restart_service: true
brew "neovim"
brew "openssl@3"
brew "parallel"
brew "pnpm"
brew "pv"
brew "r"
brew "redis", restart_service: true
brew "rpm"
brew "tmux"
brew "tree"
brew "wget"
brew "zookeeper", restart_service: true
brew "zsh"
brew "aws/tap/aws-sam-cli"
brew "cloudflare/cloudflare/cloudflared"
brew "mongodb/brew/mongodb-community"
cask "adoptopenjdk14"
cask "android-file-transfer"
cask "corretto8"
cask "discord"
cask "firefox"
cask "font-hack-nerd-font"
cask "gimp"
cask "google-chrome"
cask "imageoptim"
cask "intellij-idea-ce"
cask "iterm2"
cask "keepassxc"
cask "mysqlworkbench"
cask "ngrok"
cask "pritunl"
cask "qbittorrent"
cask "spectacle"
cask "spotify"
cask "telegram"
cask "virtualbox"
cask "visual-studio-code"
cask "visualvm"
cask "vlc"
cask "whatsapp"
mas 'The Unarchiver', id: 425424353
mas 'iMovie', id: 408981434
mas 'NordVPN', id: 905953485
mas 'QR Capture', id: 1369524274
